In [1]:
import numpy as np
import numpy.random as npr
import cvxpy as cp
import time
import matplotlib.pyplot as plt

from formulations import *
from utils import *
from vc_formulations import *


import os
import imageio

### Testing this for C5

In [2]:
n = 5

A = np.zeros((5,5)) # Adjacency matrix for C5
A[0,1] = 1
A[1,0] = 1
A[0,4] = 1
A[4,0] = 1
A[1,2] = 1
A[2,1] = 1
A[2,3] = 1
A[3,2] = 1
A[3,4] = 1
A[4,3] = 1

D = np.zeros((5,5))
D[0,0] = 1
D[0,1] = 1
D[1,1] = 1
D[1,2] = 1
D[2,2] = 1
D[2,3] = 1
D[3,3] = 1
D[3,4] = 1
D[4,4] = 1
D[4,0] = 1

In [3]:
print(A)

[[0. 1. 0. 0. 1.]
 [1. 0. 1. 0. 0.]
 [0. 1. 0. 1. 0.]
 [0. 0. 1. 0. 1.]
 [1. 0. 0. 1. 0.]]


In [35]:
w = np.ones(n)
val_c5, x_c5, y_c5 = misp(A,w,0)
val_c5_sdp, X_c5_sdp = misp_sdp(A,w,0)
val_c5_vc, x_c5_vc = vertex_cover(A,w)
val_c5_vc_sdp, x_c5_vc_sdp = vertex_cover_sdp(A,w)

In [36]:
print("optimal val = ", val_c5)
print("out sdp = ", val_c5_sdp)
print("vc-dependent sdp = ", val_c5_vc_sdp)
print("lovasz sdp = ", 2.764)

optimal val =  3.0
out sdp =  2.499983018840023
vc-dependent sdp =  1.7799734181133708
lovasz sdp =  2.764


In [25]:
x = np.array([[1,1,0,1.,0]])/np.sqrt(3)
X = x.T @ x
print(np.trace(X))

np.trace(np.ones((5,5))@ X)

1.0000000000000002


3.000000000000001

In [ ]:
val_c5_vc